// ServicesData.jsx
import { v4 as uuidv4 } from "uuid";
import {
  FaWrench,
  FaBolt,
  FaPaintBrush,
  FaHammer,
  FaFan,
  FaTools,
  FaPlug,
  FaFireExtinguisher,
  FaCogs,
  FaCouch,
  FaDoorOpen,
} from "react-icons/fa";

const servicesData = [
  {
    id: uuidv4(),
    title: "دهانات",
    desc: "دهانات وتشطيبات داخلية وخارجية",
    category: "دهانات",
    city: "القاهرة",
    artisan: "أحمد علي",
    icon: <FaPaintBrush />,
  },
  {
    id: uuidv4(),
    title: "كهرباء",
    desc: "تركيب مفاتيح، لمبات، وتمديدات كهربائية",
    category: "كهرباء",
    city: "الإسكندرية",
    artisan: "محمود سمير",
    icon: <FaBolt />,
  },
  {
    id: uuidv4(),
    title: "نجارة",
    desc: "تفصيل أبواب، نوافذ وأثاث خشبي",
    category: "نجارة",
    city: "الجيزة",
    artisan: "عماد صالح",
    icon: <FaHammer />,
  },
  {
    id: uuidv4(),
    title: "سباكة",
    desc: "تركيب وصيانة المواسير والأحواض",
    category: "سباكة",
    city: "القاهرة",
    artisan: "خالد نادر",
    icon: <FaWrench />,
  },
  {
    id: uuidv4(),
    title: "تكييف وتبريد",
    desc: "تركيب وصيانة أجهزة التكييف",
    category: "تبريد وتكييف",
    city: "الإسكندرية",
    artisan: "ياسر جمال",
    icon: <FaFan />,
  },
  {
    id: uuidv4(),
    title: "تصليح أجهزة",
    desc: "صيانة غسالات، ثلاجات وأجهزة منزلية",
    category: "صيانة أجهزة",
    city: "المنصورة",
    artisan: "سامي عبد",
    icon: <FaTools />,
  },
  {
    id: uuidv4(),
    title: "تركيب إنارة",
    desc: "تركيب وحدات إنارة داخلية وخارجية",
    category: "كهرباء",
    city: "القاهرة",
    artisan: "محمود سمير",
    icon: <FaPlug />,
  },
  {
    id: uuidv4(),
    title: "إصلاح أثاث",
    desc: "ترميم وإصلاح أثاث منزلي",
    category: "نجارة",
    city: "الشرقية",
    artisan: "عماد صالح",
    icon: <FaHammer />,
  },
  {
    id: uuidv4(),
    title: "حدادة ولحام",
    desc: "تفصيل بوابات، شبابيك، وهياكل معدنية",
    category: "حدادة",
    city: "المنوفية",
    artisan: "محمد عبد الله",
    icon: <FaCogs />,
  },
  {
    id: uuidv4(),
    title: "أنظمة إطفاء وإنذار",
    desc: "تركيب وصيانة أنظمة الحريق والإنذار المبكر",
    category: "سلامة عامة",
    city: "القاهرة",
    artisan: "إبراهيم فتحي",
    icon: <FaFireExtinguisher />,
  },
  {
    id: uuidv4(),
    title: "ديكور داخلي",
    desc: "تصميم وتنفيذ ديكورات حديثة بجودة عالية",
    category: "ديكور",
    city: "القاهرة",
    artisan: "وليد يوسف",
    icon: <FaCouch />,
  },
  {
    id: uuidv4(),
    title: "ألمنيوم ومطابخ",
    desc: "تصميم وتركيب مطابخ وأبواب ونوافذ ألمنيوم",
    category: "ألمنيوم",
    city: "الجيزة",
    artisan: "حسن علي",
    icon: <FaDoorOpen />,
  },
];

export default servicesData;
